# Generated by Django 3.2.5 on 2021-07-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_personal_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
    ]
