# Generated by Django 3.2.5 on 2021-07-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_personal_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='horas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
