# Generated by Django 3.2.5 on 2021-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210716_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
    ]
