# Generated by Django 3.2.5 on 2021-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210717_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cedula',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
