# Generated by Django 3.2.5 on 2021-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_personal_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('D', 'Dañado')], max_length=1),
        ),
    ]
