# Generated by Django 3.2.5 on 2021-07-17 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_bien_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 4, 20, 39, 423691)),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
