# Generated by Django 3.2.5 on 2021-07-17 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_reporte_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
