# Generated by Django 3.2.5 on 2021-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_permiso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='status',
            field=models.CharField(choices=[('E', 'En espera'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='E', max_length=1),
        ),
    ]
