# Generated by Django 3.2.5 on 2021-07-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_permiso_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seccion',
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='guia',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
