# Generated by Django 3.2.5 on 2021-07-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210717_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/perfiles'),
        ),
    ]
