# Generated by Django 3.2.5 on 2021-11-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_alumno_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='status',
            field=models.CharField(choices=[('E', 'En espera'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='E', max_length=1),
        ),
    ]
