# Generated by Django 3.2.5 on 2021-11-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_actividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='partipantes',
            new_name='participantes',
        ),
    ]
